name: Publish BlazorKit.CopyToClipboard on NuGet
 
on:
  push:
    branches: [ main ]
    paths: [ 'src/BlazorKit.CopyToClipboard/**' ]
  workflow_dispatch:

env:
  NETCORE_VERSION: '7.0.*'
  PROJECT_NAME: src/BlazorKit.CopyToClipboard 
  PROJECT_FILE: BlazorKit.CopyToClipboard.csproj  
  
jobs:
  build:
    name: Publish on NuGet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        
    - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}
        
    - name: Nerdbank.GitVersioning 
      uses: dotnet/nbgv@v0.4
      id: nbgv
      with:        
        path: ${{ env.PROJECT_NAME }}
        
    - name: Package
      run: dotnet pack -c Release -o . '${{ env.PROJECT_NAME }}/${{ env.PROJECT_FILE }}'
      
    - name: Publish on NuGet
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
